import Layout from 'apps/frontend/components/Layout/Layout'
import MenuBar from 'apps/frontend/components/MenuBar/MenuBar'
import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CNBC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Layout>
          <MenuBar></MenuBar>
          <div>Main Content</div>
        </Layout>
      </main>

      <footer>
       
      </footer>
    </div>
  )
}

export default Home
