# Use official node image as the base image
FROM node:16.13.1 as build

# Set the working directory
WORKDIR /usr/local/app


# Add the source code to app
COPY . /usr/local/app/

# Install angular cli
RUN npm install -g @angular/cli

# Install all the dependencies
RUN npm install -f

# Generate the build of the application
RUN npm run build:admin


# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/dist/apps/admin /usr/share/nginx/html


# Copy nginx configuration
RUN rm /etc/nginx/conf.d/default.conf
COPY frontend.nginx.conf /etc/nginx/conf.d/
RUN cd /etc/nginx/conf.d/ && mv frontend.nginx.conf default.conf


# Expose port 4400 for CLIENT
EXPOSE 4400
