FROM node:latest as build-image

WORKDIR /app
COPY . .
RUN npm install
RUN npm install pm2 -g
RUN npm run build-admin-microservice

EXPOSE 3002

CMD ["pm2-runtime", "./dist/apps/admin-microservice/main.js"]